-
  name: 'XLIFF exporter (with prefix)'
  uriPattern: '{languageKey}/{extensionKey}/{prefix}'
  defaults:
    '@package':    'Sinso.Translationapi'
    '@plugin':     'API'
    '@controller': 'Xliff'
-
  name: 'XLIFF exporter'
  uriPattern: '{languageKey}/{extensionKey}'
  defaults:
    '@package':    'Sinso.Translationapi'
    '@plugin':     'API'
    '@controller': 'Xliff'
